# Python - Numpy

## 1. ndarray生成

In [2]:
import numpy as np

In [ ]:
#一般
a = np.array([1,2,3])
a = np.array([[1,2,3],[4,5,6]])
a = np.array(range(10))                 #array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#随机数
a = np.random.random(shape)
a = np.random.randint(low,high,size)    #(low(包含),high(不包含),size)
a = np.random.normal(mean,scale,shape)

#区间数
a = np.arange(10)                 #相当于a = np.array(range(10))
a = np.arange(0,10,2)                   # (start,stop(不包括),step)    array([ 0,  2,  4,  6,  8])
a = np.linspace(10,25,5)                # (start,stop(包括),numbers)   array([ 10.,  15.,  20.,  25.])

#特殊
a = np.zeros(shape)                     #(a,b,c)
a = np.ones(shape)
a = np.empty(shape)
a = np.full(shape,fill_value)           #np.full((3,3,3),8)所有值都一样
a = np.eye(5)
a = np.identity(5)                      #都是单位矩阵

- 特别地，对角矩阵的变化

In [ ]:
i = np.eye(5)
i1 = np.eye(5,7)                       #只有对角线为1
i2 = np.eye(5,7,k=2)                   #k为正，对角线往右上移动；k为负，对角线往左下移动

## 2. 四个属性

In [ ]:
np.random.seed(0);a = np.random.randint(2,20,(3,4,5))
a.ndim           #3
a.shape          #(3, 4, 5)
a.size           #60
a.dtype          #dtype('int32')

len(a)           #层数3
len(a[0])        #每层的行数4
len(a[0][0])     #每层的列数5
                 #a.itemsize每个数占多少byte; a.nbytes数组占多大内存

- 改变array的基本数据类型

In [ ]:
a = np.random.randint(1,10,(3,4)) #改出来结果是不对的
a.dtype = float                   

a = a.astype(np.float)            #成功

## 3. 索引

In [8]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]);a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
a[:2,1:2]             #array([[2],
                      #      [6]])
a[[0,1,2],[1,2,3]]    #array([ 2,  7, 12])对应位置行列
a[:,2][::-1]          #array([11,  7,  3])

#布尔索引
a % 2 == 0 
a[a % 2 == 0 ]        #array([ 2,  4,  6,  8, 10, 12])
len(a[a % 2 == 0 ] )  # 6 矩阵中有几个符合要求的数

6

- 用切片对原矩阵进行修改

In [9]:
# 对切片进行修改会改变原矩阵
sub_a = a[1:,:2]
sub_a[1,1]=0
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  0, 11, 12]])

In [10]:
# 这样不会改变原矩阵
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]);a
sub_a = a[1:,:2]
sub_a = np.ones((2,2))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
# 也可以像list一样对使用copy进行不更改原list的复制
sub_a = a[1:,:2].copy()
sub_a = sub_a-10
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 4. array的变形、拼接、分裂

- array.reshape()
- array.concatenate()
- array.vstack()  
- array.hstack()

In [31]:
#变形
a.reshape((2,6))                     #array([[ 1,  2,  3,  4,  5,  6],
                                            #[ 7,  8,  9, 10, 11, 12]])
a.reshape((2,6)).T                #转置
    
#拼接
a1 = np.array(range(0,10))
a2 = np.array(range(10,20))
a3 = np.random.normal(0,1,(2,5))
ac = np.concatenate([a1.reshape(2,5),a2.reshape(2,5)])                       #默认：增加样本数
ac2 = np.concatenate([a1.reshape(10,1),a3.reshape(10,1)],axis=1);ac2         # axis=1 增加变量数

ac3 = np.vstack([a1,a2]);ac3        #增加样本数
#ac4 = np.hstack([a1,a2]);ac4       #增加变量数

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

- array.split()
- array.vsplit()
- array.hsplit()

In [45]:
print(a1)
a_s = np.split(a1,[2,3]);print(a_s)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1]), array([2]), array([3, 4, 5, 6, 7, 8, 9])]


In [44]:
a_s2 = np.vsplit(a1.reshape((5,2)),[2,3]);print(a1.reshape((5,2)));print(a_s2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[array([[0, 1],
       [2, 3]]), array([[4, 5]]), array([[6, 7],
       [8, 9]])]


In [47]:
a_s3 = np.hsplit(a1.reshape((2,5)),[2,3]);print(a1.reshape((2,5)));print(a_s3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[array([[0, 1],
       [5, 6]]), array([[2],
       [7]]), array([[3, 4],
       [8, 9]])]


In [54]:
a = np.array(range(0,12))
a.reshape((3,4)).T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## 函数

- 运算时间计算

In [62]:
ar1 = np.arange(1000000)
l_1 = list(range(1000000))

In [66]:
%time ar1 = ar1 * 2

Wall time: 12 ms


In [67]:
%time l_1 = [i*2 for i in l_1]

Wall time: 760 ms


- map函数

In [72]:
%time l_1 =map(lambda x:x*2,l_1)       #对列表里的每个元素，进行函数运算
l_1

Wall time: 0 ns


- reduce函数

In [ ]:
from functools import reduce
l1 = list(range(101))
l2 = int(reduce(lambda x,y:x+y,11))
print(l2)#运行结果有点问题

- 矩阵的运算

In [ ]:
ar = np.array(range(1,13)).reshape((3,4))
ar*2
ar+2.5
-ar
np.abs(-ar)
np.sin(ar)#sin cos tan arcsin
np.log(ar) #log,log2,log10,exp,exp2,power,

x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

ar_c2 * ar_c2                       #两矩阵相同位置元素相乘
ar_c2.dot(ar_c2)                    #矩阵乘法

## 6. 排序

- 一维array

In [95]:
ar = np.random.randint(0,20,20)
#升序
ar.sort();ar                      #ar已经变成排好序的了
#降序
ar=np.sort(ar)[::-1]              

array([ 0,  3, 16, 16,  9,  7, 12,  6, 12, 14, 11, 13, 17,  7, 18, 16, 10,
       11,  4, 18])

In [ ]:
#list的排序
#对于list.sort()有一个参数叫key,而np.sort()没有参数key,只能用索引降序排列
l1.sort(key = lambda x:x%3)       #对l1中元素作取余运算后的大小进行排序

In [ ]:
#取索引
np.argsort(ar)                    

- 矩阵排序

In [ ]:
mat = np.random.randint(0,20,20).reshape((4,5))
np.sort(mat,axis = 0)            #每一列内部进行排序
#np.sort(mat,axis = 1)           #每一行内部进行排序